### ISSUE TITLE
Improvement request: moving headlines around in outline view

### ISSUE THREAD

**Issue by vjjaimez** [windingwind/Knowledge4Zotero#2]
Hi! I've had a look at this new Zotero plugin and it looks very promising. I've been searching for something like this for a long time, and I'm very happy to see this becoming a reality. 
My main use case would be to create outlines for writing academic papers, etc. For this, being able to promote and demote headings, and in general move stuff around by dragging and dropping headings and chunks of text, is essential. Right now it is possible to do this in outline view, but it's a bit clunky. 
It'd be very nice to have some kind of visual clue of where things are gonna fall when dragging and dropping. The new zotero note editor does it very well (although it lacks the outline mode that your plugin introduces).
Could you improve this? Thank you!
BTW, I'd like to make a donation to kelp make this project sustainable. Is this possible? :)

**Comment by windingwind** [comment]
@vjjaimez 
Please try v0.1.3.
Drag/drop UI improvement & tons of bug fixes related to drag/drop & insert.
